services:
  db:
    image: mysql:8.4
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
volumes:
  db:
    driver: local