"""Initial revision

Revision ID: a35ad961054b
Revises: 
Create Date: 2024-05-12 20:41:35.854844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35ad961054b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('player_pkey')),
    sa.UniqueConstraint('name', name=op.f('player_name_key'))
    )
    op.create_index(op.f('player_id_idx'), 'player', ['id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['player.id'], name=op.f('match_player1_id_fkey')),
    sa.ForeignKeyConstraint(['player2_id'], ['player.id'], name=op.f('match_player2_id_fkey')),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], name=op.f('match_winner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('match_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('match_uuid_key'))
    )
    op.create_index(op.f('match_id_idx'), 'match', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('match_id_idx'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('player_id_idx'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
